<?
$aMenuLinks = array(
	array(
		'Главная',
		SITE_DIR,
		array(), 
		array(), 
		'',
	),
    array(
        'Каталог квартир',
        '/catalog/kvartiry-komnaty/',
        array(),
        array(),
        '',
    ),
    array(
        'Загородная недвижимость',
        '/catalog/doma-dachi-zemelnyy_uchastok/',
        array(),
        array(),
        '',
    ),
    array(
        'Аренда',
        '/rent/',
        array(),
        array(),
        '',
    ),
    array(
        'Ипотека',
        '/hypothec/',
        array(),
        array(),
        '',
    ),
    array(
        'Продавцу',
        '/for_seller/',
        array(),
        array(),
        '',
    ),
    array(
        'Покупателю',
        '/for_buyer/',
        array(),
        array(),
        '',
    ),
);